version: '3'

services:
  postgres:
    image: postgres:14
    command: ["postgres", "-c", "log_statement=all"]
    shm_size: 512mb
    volumes:
      - yp2_pg_volume_test:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev

volumes:
  yp2_pg_volume_test:
